### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by ricardojlrufino** [PaulStoffregen/Arduino-1.6.5r5-Teensyduino#1]
The Linux Build is not working?

I am unable to use the addon for Arduino
https://www.pjrc.com/teensy/td_124/teensyduino.64bit
It downloads as a virtual machine

**Comment by PaulStoffregen** [comment]
This is the wrong place for a tech support question.  Please post it here:

https://forum.pjrc.com/forums/3-Technical-Support-amp-Questions

When you post there, please describe in more detail "downloads as a virtual machine" (I have no idea what that means).  Maybe post a screenshot.

**Comment by ricardojlrufino** [comment]
ok, solved !
